name: CocoaPods Release

on:
  release:
    types: [released]

jobs:
  cocoapods-release:
    runs-on: macos-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: CocoaPods Release
        run: pod trunk push QonversionSandwich.podspec
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
